name: deploy
kind: pipeline
type: docker

steps:
  - name: create maven settings
    image: md5lukas/drone-mvn-settings
    settings:
      serverSecrets:
        from_secret: maven_server_secrets
  - name: deploy
    image: maven:3-jdk-11
    commands:
      - mvn deploy -B -ntp -s settings.xml

trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request
    include:
      - push
